name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test
